### ISSUE TITLE
[기능추가] 꼬리 생성

### ISSUE THREAD

**Issue by subinio** [kimkyeongnam/OSS-SnakeGame#17]
뱀이 먹이를 먹을때마다 꼬리가 생성되는 기능을 추가하여야 함.

이에 대한 comment를 남겨 주길 바람

**Comment by subinio** [comment]
스택은 낭비되는 메모리가 생길 수 있기 때문에 적합하지 않고,
단일 연결리스트는 꼬리부분을 삭제할 때, for문을 돌기때문에 시간이 많이 듭니다.

그러므로 비교적 스택보다는 메모리가 낭비되지 않고, 삽입과 삭제, 출력의 시간이 적게 드는 **이중연결리스트**로 뱀의 꼬리를 표현하고자 합니다.

이에 대한 댓글을 남겨 주세요.

**Comment by kimkyeongnam** [comment]
좋은 생각입니다!
또한 단일연결리스트보다 가독성이 좋을 것 같네요

**Comment by subinio** [comment]
그러면 구현한 후 pull request를 진행하도록 하겠습니다!!

**Comment by kimkyeongnam** [comment]
#35 구현 및 merge 완료
