### ISSUE TITLE
[기능 개선] Resize Game Map

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#23]
뱀이 움직이는 범위를 크게 하기위해 map size를 다시 조정하려합니다.
이에 대한 댓글을 남겨 주길 바랍니다.
(관련 Issue: #18)

**Comment by kimkyeongnam** [comment]
콘솔창 크기 및 맵을 재구성했는데, 충돌관련해서 약간의 문제가 있는것 같습니다 ㅠ.ㅠ..
시간날때 한번 확인 부탁해요..ㅠ
(관련 Issue: #27)

**Comment by subinio** [comment]
네 확인완료 했습니다.
