### ISSUE TITLE
[기능 개선] snake 구현

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#25]
현재 뱀을 출력하는 함수는 효율성을 떨어뜨려
효율적인 방법으로 새롭게 구현하는게 좋다고 생각합니다.
snake 구현에 관한 의견을 남겨주시길 바랍니다!

**Comment by kimkyeongnam** [comment]
Issue #17 참고

**Comment by subinio** [comment]
확인했습니다. while문을 사용하여 연결리스트를 돌아 출력하고자 합니다.

**Comment by subinio** [comment]
해당 이슈 수정 완료. (new/iss_tail) 브랜치 참조
