### ISSUE TITLE
[질문] vi 편집기 인코딩 에러

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#29]
소스코드를 업로드 시 vim을 사용하면 '■' 과 같은 특수문자들을 인식하지 못하여 "?" 와 같은 오류로 출력이 됩니다.
인터넷 검색을 통해
:dig -> ■에 해당문자 2개 찾아서 -> 편집모드로 들어가 ctrl+k -> 찾았던 문자 입력
이렇게하면 ■가 vi에 입력되는 건 알았는데, 이렇게 할 경우 E162라는 에러가 뜨면서 저장이 되지 않습니다.
해당 에러는 버퍼문제인데, 인터넷 검색 결과 저장하지 않고 끝내라고 나와 있습니다..
(물론 ㅁ->한자키->■선택 또한 되지 않습니다.)

window의 git bash와 ubuntu의 terminal을 이용했는데, 운영체제에 상관없이 vi의 오류인 것 같네요..
어떻게 할지 해결 방안을 찾아봐야 할 것 같습니다 ㅠ.ㅠ..
혹시 모르니 좀 더 정보를 찾아보긴 하겠습니다.

<br>

+vim말고도 notepad를 사용해봤는데, github에 올릴때 문제인것 같네요. notepad또한 똑같은 오류가 납니다.

**Comment by kimkyeongnam** [comment]
특수기호가 아닌, 문자로 해결하기로 결정

**Comment by subinio** [comment]
해당 오류를 확인했습니다.

뱀은
기존 : ▣  --> 변경 후 : Oo 

먹이는
기존 : ＠  --> 변경 후 : FF

보드 경계 테두리는
기존 : ■  --> 변경 후 : XX

로 변경하였습니다.

기존의 특수기호에서 알파벳 문자로 모두 변경하였습니다. 

(오류해결)
