### ISSUE TITLE
[문서화] Readme

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#30]
- [x] 무슨 프로젝트인지 전반적인 설명
- [x] 설정 및 설치 방법
- [ ] 사용법과 실행 결과에 대한 예제
- [x] 프로젝트 라이선스
- [x] 기여방법
- [x] 원제작자 및 기여자

**Comment by kimkyeongnam** [comment]
https://github.com/kimkyeongnam/OSS-SnakeGame/blob/readme/README.md

프로토타입 생성 완료.
코드수정 완료 후 세부사항 및 고쳐야 할 내용 수정 예정

**Comment by subinio** [comment]
확인.
