### ISSUE TITLE
[문서화] Manage topics & Description

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#31]
![사진](https://user-images.githubusercontent.com/38516906/58498633-68481c80-81b9-11e9-8686-5f0b0c8db49f.png)

topic 및 description 수정

**Comment by kimkyeongnam** [comment]
![1](https://user-images.githubusercontent.com/38516906/58499088-5f0b7f80-81ba-11e9-831d-e137a1b6a92d.png)

수정해봤는데 어떤지 피드백 부탁해요!

**Comment by subinio** [comment]
좋습니다!!
