### ISSUE TITLE
[문서화] Wiki

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#32]
**Issue #30 : README** 보다 자세하게 설명
- [x] 공유할 정보
- [x] 개발 문서
- [x] 참고 자료
- [x] 프로젝트 세부 설명
- [x] 프로젝트 라이선스
- [x] 원작자 및 기여자

**Comment by kimkyeongnam** [comment]
* [Add functions of open source code](https://github.com/kimkyeongnam/OSS-SnakeGame/wiki/3.-Project-Execution-Plan#add-functions-of-open-source-code)
* [Development Record](https://github.com/kimkyeongnam/OSS-SnakeGame/wiki/4.-Development-Record)
이외의 모든 항목 작성 완료

Add functions of open source code와 Development Record는 코드 수정완료 후 작성 예정

**Comment by kimkyeongnam** [comment]
https://github.com/kimkyeongnam/OSS-SnakeGame/wiki/1.-Project-Overview#project-topic-snake-game
그림 출처 작성부탁해요 이뿐이ㅎ.ㅎ

**Comment by subinio** [comment]
네넹ㅇ

**Comment by kimkyeongnam** [comment]
확인했습니다. 감사합니당
