### ISSUE TITLE
[Ver. ] 태그(버전) 작성

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#33]
해당 내용을 참고로 태그 작성해주시길 바랍니다.
![버전](https://user-images.githubusercontent.com/38516906/58529984-e5a27a00-8217-11e9-8796-b27505eb1ce5.png)
<br><br>

Last Update: 29.05.2019
Reference Issue #4

**Comment by kimkyeongnam** [comment]
확인 작업
- [ ]
- [ ]
- [ ]

**Comment by kimkyeongnam** [comment]
# 1. InitMap()
내용

**Comment by kimkyeongnam** [comment]
# 2. DrawMap()
내용

**Comment by kimkyeongnam** [comment]
# 2. GetInput()\
내용

**Comment by kimkyeongnam** [comment]
# 3. EatFood()
내용

**Comment by kimkyeongnam** [comment]
# 4. Die()
내용

**Comment by kimkyeongnam** [comment]
# 5. main()
내용

**Comment by subinio** [comment]
확인 완료 했습니다.

x에 관해서..

0: 기존 코드
**1.5: 클린코드**
1: OSS수업 최종본
2: OSS수업이 끝나도 코드를 계속 발전시켜 대규모 업데이트를 했을 경우

는 별로일까요?

**Comment by kimkyeongnam** [comment]
# 5. main()
|함수 이름|Commit Number|붙인 Tag|
|:--:|:--:|:--:|
|main|||

**Comment by kimkyeongnam** [comment]
# 6. MoveSnake()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|MoveSnake||||

**Comment by kimkyeongnam** [comment]
# 7. GetInput()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|GetInput||||

**Comment by kimkyeongnam** [comment]
# 8. EatFood()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|EatFood||||

**Comment by kimkyeongnam** [comment]
# 9. ChkSnakeDie()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|ChkSnakeDie||||

**Comment by kimkyeongnam** [comment]
# 10. DrawTitle()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 11. DrawScore()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 12. DrawMap()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 13. DrawFood()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 14. SetCurrentCursorPos()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 15. RemoveCursor()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 16. RelocateFood()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 17. RelocateSnake()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 18. IsCollisionTopBorder()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 19. IsCollisionBottomBorder()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 20. IsCollisionLeftBorder()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 21. IsCollisionRightBorder()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 22. AddTail()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 23. DelAllTail()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 24. ChkOppositeDir()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||

**Comment by kimkyeongnam** [comment]
# 25. FreeAllMemories()
|함수 이름|Commit Number|붙인 Tag|관련 Issue|
|:--:|:--:|:--:|:--:|
|||||
