### ISSUE TITLE
[필독] 키보드 오류 아닌거같아

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/OSS-SnakeGame#5]
입력이 HKPM이게 아니라 
방향키보드 그거같아
수빈아 너도 한번 돌려봐바
오..이런..

**Comment by subinio** [comment]
완성된거 같지 않아 보이는 코드로 새로 찾아 봄.
주소 : https://github.com/abdulwahid2802/SnakeGame/blob/master/main.c

**Comment by kimkyeongnam** [comment]
그러면 말했던것처럼 이거로 변경하자!
코드는 이걸로 바꿔놓을게~
