### ISSUE TITLE
clean/origin branch merge to master

### ISSUE THREAD

**Issue by subinio** [kimkyeongnam/OSS-SnakeGame#9]
|수정내용|merge날짜|관련 Pull Requests|
|:--:|:--:|:--:|
|헤더파일 작성법 수정<br>전역 변수 정리 및 init() 함수 생성|05.10| |
|상수를 매직넘버로 수정<br>boolean역할하는 변수 define<br>MoveSnake()안의 조건식을 함수로 변경<br>IsCollisionTopBorder(),<br>IsCollisionBottomBorder(),<br>IsCollisionLeftBorder(),<br>IsCollisionRightBorder() 함수 생성|05.19|#15 |
| Die함수이름 및 매개변수 a이름 변경<br>RelocateFood(), RelocateSnake()함수 생성|05.20|#16 |

<br><br>

### 05.15
이후 merge의견은 Pull requests로 확인 및 댓글 작성
Issue에는 해당 merge내용 및 관련 Issue 표로 작성

**Comment by subinio** [comment]
변수명은 이후 함수의 수정에 의해 다시 변경될 수 있음.

**Comment by kimkyeongnam** [comment]
> 변수명은 이후 함수의 수정에 의해 다시 변경될 수 있음.

네네 좋아요~~ 수고했어요!

**Comment by subinio** [comment]
|수정내용|merge날짜|
|:--:|:--:|
|전역 변수 정리 및 init() 함수 생성|05.10|
